import type { Metadata } from "next";
import "./globals.css";
import TopBadge from "@/components/feature/TopBadge/TopBadge";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link href="https://fonts.googleapis.com/css2?family=Krona+One&display=swap" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css2?family=Wix+Madefor+Display:wght@400..800&display=swap" rel="stylesheet"></link>
      </head>
      <body
        className={` w-full h-screen bg-white flex flex-col`}
      >
        <TopBadge />
        <div className="flex-1">
          {children}
        </div>
      </body>
    </html>
  );
}
