import type { Metadata } from "next";
import "./globals.css";
import TopBadge from "@/components/feature/TopBadge/TopBadge";
import Image from "next/image";
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger } from "@/components/ui/dropdown-menu";
import Link from "next/link";
import Container from "@/components/common/Container";
import Menu from "@/assets/Menu";
import { Sheet, SheetTrigger, SheetContent, SheetHeader, SheetTitle, SheetDescription } from "@/components/ui/sheet";
import LeftBadge from "@/components/feature/LeftBadge/LeftBadge";
import Footer from "@/components/common/Footer";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function LinkItem({ href, title }: { title: string, href: string }) {
  return <Link href={href} className="text-sm text-tint hover:text-tint-alt">
    {title}
  </Link>
}



function AppBar() {
  return (
    <div className="">
      <Container className="flex !py-3 !flex-row justify-between items-center uppercase">
        <div className="w-full lg:w-fit flex justify-between items-center">
          {/* Mobile Menu */}
          <div className="lg:hidden">
            <Sheet>
              <SheetTrigger asChild>
                <button>
                  <Menu className="text-2xl" />
                </button>
              </SheetTrigger>
              <SheetContent side="left" className="p-4">
                <SheetHeader>
                  <SheetTitle>Menu</SheetTitle>
                </SheetHeader>
                <div className="flex flex-col gap-y-4">
                  <LinkItem href="/" title="Home" />
                  <LinkItem href="/about" title="About us" />
                  <LinkItem href={`/courses`} title={'Courses ▼'} />
                  <LinkItem href="/placements" title="Placements" />
                  <LinkItem href="/gallery" title="Gallery" />
                  <LinkItem href="/contact" title="Contact Us" />
                  <LinkItem href="/blog" title="Blog" />
                </div>
              </SheetContent>
            </Sheet>
          </div>
          {/* Logo */}
          <Image src={"/images/logo.png"} width={186} height={58} alt="Logo" />
          <div></div>
        </div>
        {/* Desktop Menu */}
        <div className="hidden lg:flex items-center gap-x-5">
          {["Home", "About us"].map((i) => (
            <LinkItem key={i} href={`/${i.toLowerCase().replace(" ", "-")}`} title={i} />
          ))}
          <LinkItem href={`/`} title={'Courses ▼'} />
          {["Placements", "Gallery", "Contact Us", "Blog"].map((i) => (
            <LinkItem key={i} href={`/${i.toLowerCase().replace(" ", "-")}`} title={i} />
          ))}
        </div>
      </Container>
    </div>
  );
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link href="https://fonts.googleapis.com/css2?family=Krona+One&display=swap" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css2?family=Wix+Madefor+Display:wght@400..800&display=swap" rel="stylesheet"></link>
      </head>
      <body className={`w-full h-screen bg-white flex flex-col`}>
        <TopBadge />
        <AppBar />
        <LeftBadge />
        <div className="flex-1">
          {children}
        </div>
        <Footer/>
      </body>
    </html>
  );
}
